targets:
  $default:
    builders:
      gaply|gaply_preset_builder:
        enabled: true
        generate_for:
          - lib/src/**
          
builders:
  gaply_preset_builder:
    import: "package:gaply/src/generator.dart"
    builder_factories: ["gaplyPresetBuilder"]
    build_extensions: {".dart": [".preset.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]