name: gaply

description: >
  A utility-first Flutter UI kit that fills the gaps in standard widgets. 
  Focuses on seamless animations, enhanced text styling, and status-aware forms.

version: 0.0.1

publish_to: none

homepage: https://github.com/friend-22/gaply
repository: https://github.com/friend-22/gaply
issue_tracker: https://github.com/friend-22/gaply/issues
documentation: https://pub.dev/packages/gaply

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  shimmer: ^3.0.0
  source_gen: ^1.5.0
  build: ^2.4.1
  analyzer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
