name: Deploy Live Demo
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: demo

      - name: Build Web
        run: flutter build web --base-href /gaply/ --release
        working-directory: demo
            
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demo/build/web
          branch: gh-pages
          clean: true
          force: true
          single-commit: true